In [1]:
# house prices 


In [2]:
import numpy as np
import pandas as pd

In [3]:
# generate 100 random numbers between [0, 1)
prices = np.random.default_rng(seed=1).random(size=100)

In [4]:
# rescale between 100K and 500K
prices = prices  * 400 + 100

In [5]:
prices

array([304.72864988, 480.18547853, 157.66384509, 479.45977885,
       224.7325808 , 269.33057959, 431.08103753, 263.67965455,
       319.83747507, 111.0236453 , 401.40524347, 315.25732529,
       231.8926866 , 415.37148137, 221.27793172, 281.39915579,
       153.6166789 , 261.24519458, 181.38209627, 204.92533618,
       400.14586905, 212.16350319, 294.07638977, 492.29487992,
       484.66287747, 389.91597631, 316.49074222, 210.75648162,
       164.26080351, 487.97016529, 306.42743422, 146.34624499,
       349.39590222, 410.67324574, 345.20132042, 466.91908192,
       115.83715067, 311.4357053 , 283.73435315, 124.93983166,
       356.53126766, 441.05313539, 337.17640724, 204.03897909,
       435.95260841, 303.79835261, 304.35555379, 401.21208308,
       159.16881431, 427.85068765, 373.3147624 , 414.83877662,
       176.64650361, 420.94566445, 176.52957042, 132.62104695,
       442.09078971, 444.51339847, 450.61483857, 288.76388774,
       209.61935545, 102.83673144, 358.28835823, 387.96

In [6]:
# no of bedrooms between 1 and 4
bedrooms = np.random.default_rng(seed=0).integers(low=1, high=5, size=100)
bedrooms

array([4, 3, 3, 2, 2, 1, 1, 1, 1, 4, 3, 4, 3, 3, 4, 3, 3, 3, 3, 4, 2, 4,
       3, 1, 2, 4, 3, 1, 4, 3, 4, 1, 1, 4, 1, 3, 1, 2, 2, 2, 2, 1, 1, 1,
       1, 3, 3, 3, 2, 3, 4, 2, 2, 4, 4, 4, 2, 3, 4, 3, 4, 3, 3, 2, 4, 1,
       3, 3, 4, 3, 2, 2, 2, 2, 3, 4, 1, 4, 3, 2, 3, 3, 2, 2, 3, 3, 3, 2,
       4, 2, 2, 4, 2, 1, 3, 3, 1, 1, 2, 4], dtype=int64)

In [7]:
# size in square foot
square_foot = np.random.default_rng(seed=2).integers(low=50, high=200, size=100)
square_foot

array([175,  89,  66,  94, 112, 172, 117,  63, 100, 140, 171, 159, 198,
        78, 182,  58, 133,  91,  80, 148,  95, 134,  89,  72, 162, 114,
       151, 150, 191, 113,  82, 144, 190, 195, 180, 152, 107, 108,  55,
        78,  99, 101, 136, 126, 153, 183, 181, 166, 196,  97, 186, 188,
        83, 120, 135, 154, 155,  66, 121,  65, 193,  80, 117, 182, 128,
       151, 124, 177, 139, 146, 118, 110, 139, 127, 167, 139, 120, 179,
        81, 115, 122, 183, 116, 142,  61, 174, 116, 124,  64, 153, 144,
       100, 165, 128,  58,  82,  88,  65, 125,  55], dtype=int64)

In [8]:
# bathrooms 
bedrooms = np.random.default_rng(seed=3).integers(low=1, high=3, size=100)
bedrooms

array([2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1,
       2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2,
       2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2,
       2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1], dtype=int64)

In [9]:
# has parking 
parking = np.random.default_rng(seed=4).integers(low=0, high=2, size=100)
parking

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0], dtype=int64)